### ISSUE TITLE
Unsure on how to get this working

### ISSUE THREAD

**Issue by Anexzs** [01Pollux/FF2ConfigToVSH2#1]
How are you supposed to run the script? I put the files in tf/addons/scripting, but it doesn't seem to do anything.

**Comment by JassJam** [comment]
Compile and put the smx file inside the plugins folder, after that **it will** modify the configs you have for ff2, so back them up if needed.

**Comment by Anexzs** [comment]
> Compile and put the smx file inside the plugins folder, after that **it will** modify the configs you have for ff2, so back them up if needed.

C:\Users\User\Downloads\TF2 Server\tf\addons\sourcemod\scripting\ff2_config_to_vsh2.sp(173) : error 139: could not find type "FF2DefaultsToVSH2"
//

What I get when compiling

**Comment by JassJam** [comment]
I apologize for the delayed answer.
the lasted commit 61cb889 contains the fixed issue.

**Comment by Anexzs** [comment]
Sorry for saying this so late, but it seems to not be converting the actual CFGs themselves but rather just characters.cfg, unless that's intended? I'm suspecting it could be why I'm getting weird errors like:
**L 05/28/2023 - 13:11:35: [freak_fortress_2.smx] [VSH2/FF2] Character "venom" is missing file "sound\freak_fortress_2\venom      heme2.mp3"!**
Despite the said file either existing, or the console outputs a file that doesn't exist.

**Comment by JassJam** [comment]
> Sorry for saying this so late, but it seems to not be converting the actual CFGs themselves but rather just characters.cfg, unless that's intended?

That was the intended behaviour, it only modifies the boss' config, not 'characters.cfg'.

**Comment by Anexzs** [comment]
> That was the intended behaviour, it only modifies the boss' config, not 'characters.cfg'.

I meant it modifies only **characters.cfg** with enums as opposed to modifying the bosses as well.
